import type { MileageItem } from "@/types/mileage";

export const MOCK_CLIENTS = [
  { id: "c1", companyName: "Acme Corp" },
  { id: "c2", companyName: "TechStart Ltd" },
  { id: "c3", companyName: "Green Solutions" },
  { id: "c4", companyName: "Nordic Ventures" },
  { id: "c5", companyName: "Pacific Dynamics" },
];

export const MOCK_MILEAGES: MileageItem[] = [
  {
    id: "m1",
    name: "Client site visit – Acme Corp HQ",
    note: "Quarterly review meeting",
    occurDate: "2025-06-15",
    client: { id: "c1", companyName: "Acme Corp" },
    quantity: 45.2,
    unit: "mi",
    startMileage: null,
    finishMileage: null,
    roundTrip: false,
    price: 0.67,
    subtotal: 30.28,
    currency: "USD",
    reimbursable: true,
    report: true,
    entryMode: "manual",
    createdAt: "2025-06-15T10:00:00Z",
  },
  {
    id: "m2",
    name: "Airport pickup – TechStart team",
    note: "",
    occurDate: "2025-06-10",
    client: { id: "c2", companyName: "TechStart Ltd" },
    quantity: 62.0,
    unit: "mi",
    startMileage: 12450,
    finishMileage: 12512,
    roundTrip: true,
    price: 0.67,
    subtotal: 41.54,
    currency: "USD",
    reimbursable: false,
    report: false,
    entryMode: "odometer",
    createdAt: "2025-06-10T14:30:00Z",
  },
  {
    id: "m3",
    name: "Green Solutions warehouse inspection",
    note: "Monthly compliance check",
    occurDate: "2025-05-28",
    client: { id: "c3", companyName: "Green Solutions" },
    quantity: 18.5,
    unit: "mi",
    startMileage: null,
    finishMileage: null,
    roundTrip: false,
    price: 0.67,
    subtotal: 12.40,
    currency: "USD",
    reimbursable: true,
    report: false,
    entryMode: "manual",
    createdAt: "2025-05-28T09:00:00Z",
  },
  {
    id: "m4",
    name: "Nordic Ventures investor meeting",
    note: "",
    occurDate: "2025-05-20",
    client: { id: "c4", companyName: "Nordic Ventures" },
    quantity: 112.0,
    unit: "km",
    startMileage: 8930,
    finishMileage: 9042,
    roundTrip: false,
    price: 0.42,
    subtotal: 47.04,
    currency: "EUR",
    reimbursable: true,
    report: true,
    entryMode: "odometer",
    createdAt: "2025-05-20T11:00:00Z",
  },
  {
    id: "m5",
    name: "Pacific Dynamics office delivery",
    note: "Sample products delivery",
    occurDate: "2025-05-14",
    client: { id: "c5", companyName: "Pacific Dynamics" },
    quantity: 28.0,
    unit: "mi",
    startMileage: null,
    finishMileage: null,
    roundTrip: true,
    price: 0.67,
    subtotal: 18.76,
    currency: "USD",
    reimbursable: false,
    report: false,
    entryMode: "manual",
    createdAt: "2025-05-14T13:00:00Z",
  },
  {
    id: "m6",
    name: "Downtown office commute – Acme project",
    note: "On-site development sprint",
    occurDate: "2025-05-08",
    client: { id: "c1", companyName: "Acme Corp" },
    quantity: 24.6,
    unit: "mi",
    startMileage: 11200,
    finishMileage: 11224.6,
    roundTrip: false,
    price: 0.67,
    subtotal: 16.48,
    currency: "USD",
    reimbursable: true,
    report: true,
    entryMode: "odometer",
    createdAt: "2025-05-08T08:30:00Z",
  },
  {
    id: "m7",
    name: "Conference – Annual Tech Summit",
    note: "3-day developer conference",
    occurDate: "2025-04-22",
    client: null,
    quantity: 210.0,
    unit: "km",
    startMileage: null,
    finishMileage: null,
    roundTrip: true,
    price: 0.42,
    subtotal: 88.20,
    currency: "EUR",
    reimbursable: true,
    report: false,
    entryMode: "manual",
    createdAt: "2025-04-22T07:00:00Z",
  },
  {
    id: "m8",
    name: "TechStart product demo",
    note: "",
    occurDate: "2025-04-15",
    client: { id: "c2", companyName: "TechStart Ltd" },
    quantity: 33.4,
    unit: "mi",
    startMileage: 10800,
    finishMileage: 10833.4,
    roundTrip: false,
    price: 0.67,
    subtotal: 22.38,
    currency: "USD",
    reimbursable: false,
    report: true,
    entryMode: "odometer",
    createdAt: "2025-04-15T10:00:00Z",
  },
  {
    id: "m9",
    name: "Supply run – Green Solutions",
    note: "Picked up office supplies",
    occurDate: "2025-04-05",
    client: { id: "c3", companyName: "Green Solutions" },
    quantity: 12.0,
    unit: "mi",
    startMileage: null,
    finishMileage: null,
    roundTrip: false,
    price: 0.67,
    subtotal: 8.04,
    currency: "USD",
    reimbursable: true,
    report: false,
    entryMode: "manual",
    createdAt: "2025-04-05T15:00:00Z",
  },
  {
    id: "m10",
    name: "Nordic HQ strategy workshop",
    note: "Full day workshop",
    occurDate: "2025-03-28",
    client: { id: "c4", companyName: "Nordic Ventures" },
    quantity: 340.0,
    unit: "km",
    startMileage: 7500,
    finishMileage: 7840,
    roundTrip: false,
    price: 0.42,
    subtotal: 142.80,
    currency: "EUR",
    reimbursable: true,
    report: true,
    entryMode: "odometer",
    createdAt: "2025-03-28T06:00:00Z",
  },
  {
    id: "m11",
    name: "Pacific Dynamics site survey",
    note: "New project kick-off",
    occurDate: "2025-03-15",
    client: { id: "c5", companyName: "Pacific Dynamics" },
    quantity: 55.8,
    unit: "mi",
    startMileage: null,
    finishMileage: null,
    roundTrip: true,
    price: 0.67,
    subtotal: 37.39,
    currency: "USD",
    reimbursable: false,
    report: false,
    entryMode: "manual",
    createdAt: "2025-03-15T09:30:00Z",
  },
  {
    id: "m12",
    name: "Bank & post office errands",
    note: "Administrative tasks",
    occurDate: "2025-03-10",
    client: null,
    quantity: 8.2,
    unit: "mi",
    startMileage: null,
    finishMileage: null,
    roundTrip: false,
    price: 0.67,
    subtotal: 5.49,
    currency: "USD",
    reimbursable: false,
    report: false,
    entryMode: "manual",
    createdAt: "2025-03-10T11:00:00Z",
  },
];
